version: 2.1

environment:
  CIRCLE_WORKING_DIRECTORY: ~/nest

orbs:
  node: circleci/node@4.5.1

parameters:
  node-executor:
    type: string
    default: node/default

jobs:
  build:
    executor: << pipeline.parameters.node-executor >>
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run:
          name: Run npm build
          command: npm run build
  lint:
    executor: << pipeline.parameters.node-executor >>
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Lint
          command: npm run lint
      - run:
          name: Lint commit
          command: ./node_modules/.bin/commitlint-circle -c .commitlintrc.json
  integration_tests:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: "12"
      - setup_remote_docker:
          version: 19.03.13
      - node/install-packages
      - run:
          name: Prepare tests
          command: |
            bash ./scripts/prepare.sh
            sleep 10
      - run:
          name: List running containers
          command: docker ps
      - run:
          name: Run Integration Tests
          command: npm run test:integration
  codechecks_benchmarks:
    executor: << pipeline.parameters.node-executor >>
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run npm Build
          command: npm run build
      - run:
          name: Install native wrk
          command: .circleci/install-wrk.sh
      - run:
          name: Run codechecks with benchmarks
          command: yarn codechecks:benchmarks
  samples:
    executor: << pipeline.parameters.node-executor >>
    environment:
      DISABLE_OPENCOLLECTIVE: "true"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build Samples
          command: npm run build:samples

workflows:
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - integration_tests:
          requires:
            - build
      - codechecks_benchmarks:
          requires:
            - build
      - samples:
          requires:
            - build
      - node/test:
          requires:
            - build
          matrix:
            parameters:
              version:
                - "10"
                - "12"
                - "14"
                - "16"