version: 2.1

parameters:
  node-version:
    type: string
    default: "12.22.3"

orbs:
  node: circleci/node@4.5.1

jobs:
  lint:
    docker:
      - image: cimg/node:12.22.3
    steps:
      - run:
          name: Run npm lint
          command: npm run lint
      - run:
          name: Lint commit
          command: ./node_modules/.bin/commitlint-circle -c .commitlintrc.json
  integration_tests:
    docker:
      - image: cimg/node:12.22.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Prepare tests
          command: |
            bash ./scripts/prepare.sh
            sleep 10
      - run:
          name: List running containers
          command: docker ps
      - run:
          name: "12.22.3"
          command: test:integration
  codechecks_benchmarks:
    docker:
      - image: cimg/node:12.22.3
    steps:
      - run:
          name: Run npm build
          command: npm run build
      - run:
          name: Install native wrk
          command: .circleci/install-wrk.sh
      - run:
          name: Run codechecks with benchmarks
          command: yarn codechecks:benchmarks
  samples:
    docker:
      - image: cimg/node:12.22.3
    steps:
      - run:
          name: Run codechecks 
          command: npm run build:samples
          environment:
            DISABLE_OPENCOLLECTIVE: "true"

workflows:
  build-test-check:
    jobs:
      - node/test:
          version: << pipeline.parameters.node-version >>
          run-command: build
      - lint:
          requires:
            - node/test
      - codechecks_benchmarks:
          requires:
            - node/test
      - samples:
          requires:
            - node/test
  build-test-multiple:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - "10.24.1"
                - "12.22.3"
                - "14.17.3"
                - "16.5.0"