version: 2.1

orbs:
  node: circleci/node@4.5.1

jobs:
  build-lint-codecheck:
    docker:
      - image: cimg/node:12.22.3
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run:
          name: Run npm lint
          command: npm run lint
      - run:
          name: Lint commit
          command: ./node_modules/.bin/commitlint-circle -c .commitlintrc.json
      - run:
          name: Install native wrk
          command: .circleci/install-wrk.sh
      - run:
          name: Run codechecks with benchmarks
          command: yarn codechecks:benchmarks
  build-samples:
    docker:
      - image: cimg/node:12.22.3
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run:
          name: Run codechecks 
          command: npm run build:samples
          environment:
            DISABLE_OPENCOLLECTIVE: "true"
  integration_tests:
    docker:
      - image: cimg/node:12.22.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Prepare tests
          command: |
            bash ./scripts/prepare.sh
            sleep 10
      - run:
          name: List running containers
          command: docker ps
      - node/install-packages
      - run:
          name: Run Integration Tests
          command: npm run test:integration

workflows:
  build-test-check:
    jobs:
      - build-lint-codecheck
      - build-samples:
          requires:
            - build-lint-codecheck
      - integration_tests:
          requires:
            - build-lint-codecheck
  test-multiple-node-versions:
    jobs:
      - node/test:
          run-command: build test
          matrix:
            parameters:
              version:
                - "10.24.1"
                - "12.22.3"
                - "14.17.3"
                - "16.5.0"